server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
        - AddResponseHeader=X-Gateway, RedNorte-Gateway
      routes:
        - id: service-centros
          uri: lb://service-centros
          predicates:
            - Path=/api/centros/**

        - id: service-recursos-salas
          uri: lb://service-recursos
          predicates:
            - Path=/api/salas/**

        - id: service-recursos-equipamiento
          uri: lb://service-recursos
          predicates:
            - Path=/api/equipamiento/**

        - id: service-pacientes
          uri: lb://service-pacientes
          predicates:
            - Path=/api/pacientes/**

        - id: service-medicos
          uri: lb://service-medicos
          predicates:
            - Path=/api/medicos/**

        - id: service-citas
          uri: lb://service-citas
          predicates:
            - Path=/api/citas/**

        - id: service-fichas
          uri: lb://service-fichas
          predicates:
            - Path=/api/fichas/**

        - id: service-farmacia
          uri: lb://service-farmacia
          predicates:
            - Path=/api/farmacia/**

        - id: service-laboratorio
          uri: lb://service-laboratorio
          predicates:
            - Path=/api/laboratorio/**

        - id: service-urgencias
          uri: lb://service-urgencias
          predicates:
            - Path=/api/urgencias/**

        - id: service-notificaciones
          uri: lb://service-notificaciones
          predicates:
            - Path=/api/notificaciones/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:host.docker.internal}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: api-gateway:8080
    non-secure-port: 8080
    ip-address: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: INFO
